#!/bin/sh

VER=1.3

./mkinfo ${VER}

if make VERSION=${VER}
then
	./bin/hd \
	-v ${VER} \
	-n hd \
	-o ./obj \
	-b ./bin \
	-f -g -f -Wall -f -Wextra -f -O2 -f -std=gnu18 -f -D_GNU_SOURCE \
	-l msap -l macsv \
	-s ./src \
	-i ./inc \
	-i ./snp \
	-m makefile.test \
	-T ./src/main.c \
	-S
fi
