#!/bin/sh

VER=1.2

./mkinfo ${VER}

make VERSION=${VER}

./bin/hd \
-v ${VER} \
-n hd \
-o ./obj \
-b ./bin \
-f -g -f -Wall -f -Wextra -f -O2 -f -std=gnu18 \
-l msap -l macsv \
-s ./src \
-i ./inc \
-i ./snp
